/* HPFFL Archives — photo manifest.
   Add one entry per picture. Drop the image file itself into the photos/ folder.

   file     (required) filename inside photos/  e.g. "2011-trophy-night.jpg"
   year     (optional) season the photo belongs to. Omit for undated/general.
   team     (optional) franchise name, spelled exactly as it appears in the app.
   teams    (optional) use instead of "team" to tag several franchises:
            teams: ["War Pigs", "Unforgiven"] — the photo appears on every
            tagged team's page. The first name is the Gallery's click target.
   caption  (optional) shown under the photo. Falls back to the filename.
   sort     (optional) lower numbers come first inside a year.

   Keep images ~1600px wide and under ~400KB so the page stays fast.
*/
window.HPFFL_PHOTOS = [
  // { file: "2011-trophy-night.jpg", year: 2011, team: "Reservoir Dogs", caption: "Trophy night" },
  // { file: "2004-warpigs-unforgiven.jpg", year: 2004, teams: ["War Pigs", "Unforgiven"], caption: "Week 9 grudge match" },
  // { file: "1999-original-trophy.jpg", caption: "The original trophy" }
  { file: "2004 HPFFL Draft 001 Large.jpeg", year: 2004, teams: ["War Pigs", "The Unforgiven", "Austin Rounders", "Pipemasters"], caption: "Garden Room Draft, Worm highlighting his 12th round sleeper"},
  { file: "2004 HPFFL Draft 002 Large.jpeg", year: 2004, teams: ["Pipemasters", "Reservoir Dogs"], caption: "Let me consult this magazine that was printed 3 months ago..."},
  { file: "2004 HPFFL Draft 003 Large.jpeg", year: 2004, teams: ["Nytebyrd"], caption: "Another successful year drafting Joe Horn"},
  { file: "2004 HPFFL Draft 004 Large.jpeg", year: 2004, teams: ["Trainwreck"], caption: "Roy Williams attends the HPFFL Draft"},
  { file: "2004 HPFFL Draft 005 Large.jpeg", year: 2004, teams: ["Chitown Maulers", "Predator", "Beefmaster", "Trainwreck"], caption: "Smoke break"},
  { file: "2004 HPFFL Draft 006 Large.jpeg", year: 2004, teams: ["Austin Rounders", "Reservoir Dogs", "War Pigs", "Peace Pipes"], caption: "Leland hit the dugout too hard"},
  { file: "2004 HPFFL Draft 007 Large.jpeg", year: 2004, teams: ["Beefmaster", "Austin Rounders", "Chitown Maulers", "Dark Horse", "Grim Outlook"], caption: "Where's the beef???"},
  { file: "2004 HPFFL Draft 008 Large.jpeg", year: 2004, teams: ["Predator"], caption: "Nice shirt"},
  { file: "56876072961__C02D561C-AD3A-4286-B40E-DB375AE2FBC5 Large.jpeg", year: 2019, teams: ["Paranoid Androids"], caption: "Solid gold!"},
  { file: "58715231934__9D74BDFA-CA49-4694-9BAC-A867CCE2F5BF Large.jpeg", year: 2019, caption: "Balls waiting to be fondled"},
  { file: "58838257348__3630AA45-4430-401E-B83E-907675E261F0 Large.jpeg", year: 2019, teams: ["Paranoid Androids"], caption: "Da commish"},
  { file: "59392162336__5F4F31EF-80D7-451D-843F-D814FE5C8EEA Large.jpeg", year: 2019, teams: ["Paranoid Androids"], caption: "Everything in its right place"},
  { file: "65065913532__12EE5B82-0A2C-4AC1-BE1C-617F8FD7B614.fullsizerender Large.jpeg", year: 2021, caption: "Crown Jewels"},
  { file: "68209693712__A0703735-5BEF-4E28-B177-B5B3F34F49F9 Large.jpeg", year: 2022, caption: "Ready for the Lottery"},
  { file: "CIMG0071 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "T.O. exorcism Pt. 1"},
  { file: "CIMG0072 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "T.O. exorcism Pt. 2"},
  { file: "CIMG0073 Large.jpeg", year: 2006, teams: ["Predator", "Peace Pipes", "Inglorious Basterdz"], caption: "Brenton concert"},
  { file: "CIMG0084 Large.jpeg", year: 2006, caption: "T.O. exorcism Pt. 3"},
  { file: "CIMG0085 Large.jpeg", year: 2006, caption: "T.O. exorcism Pt. 4"},
  { file: "DB14F1E2-441A-4AE1-8CB4-FAB5481192BE Large.jpeg", year: 2018, teams: ["Reservoir Dogs"], caption: "Dogs plate #3"},
  { file: "DSC00147 Large.jpeg", year: 2008, teams: ["Trainwreck", "Dark Horse"], caption: "Wreck's first chip"},
  { file: "DSC00148 Large.jpeg", year: 2008, teams: ["Trainwreck"], caption: "We'd like to thank AD and Tony Romo"},
  { file: "DSC00149 Large.jpeg", year: 2008, teams: ["Paranoid Androids"], caption: "Commish and Commish Jr."},
  { file: "DSC00150 Large.jpeg", year: 2008, teams: ["Paranoid Androids"], caption: "The face of a kid who would go on to have no interest in football whatsoever"},
  { file: "DSC00151 Large.jpeg", year: 2008, teams: ["Paranoid Androids", "Nytebyrd", "Trainwreck", "Dark Horse", "Predator"], caption: "Championship Mug convention"},
  { file: "DSC00152 Large.jpeg", year: 2008, teams: ["Paranoid Androids", "Nytebyrd", "Trainwreck", "Dark Horse", "Predator"], caption: "Strike a pose"},
  { file: "DSC00153 Large.jpeg", year: 2008, teams: ["Paranoid Androids"], caption: "These ARE the Droids you're looking for"},
  { file: "DSC00180 Large.jpeg", year: 2008, caption: "High-tech ball stops"},
  { file: "DSC00182 Large.jpeg", year: 2008, teams: ["Paranoid Androids"], caption: "Commish drafts from the beach"},
  { file: "DSC00203 Large.jpeg", year: 2008, teams: ["Paranoid Androids"], caption: "Droid mug"},
  { file: "DSC00204 Large.jpeg", year: 2009, teams: ["Chuck 'n Ducks"], caption: "Still made about the tiebreaker rule"},
  { file: "Droids Large.jpeg", year: 2007, teams: ["Paranoid Androids"], caption: "Skinny commish and fellow Droid at Thurman's Mansion"},
  { file: "IMG_0054 Large.jpeg", year: 2023, teams: ["Predator"], caption: "Dale Dale Dale ATX!"},
  { file: "IMG_0055 Large.jpeg", year: 2023, caption: "Crown Jewels in a crack"},
  { file: "IMG_0056 Large.jpeg", year: 2023, teams: ["Franco's Fur Coats"], caption: "CMC Music Factory"},
  { file: "IMG_0057 Large.jpeg", year: 2023, teams: ["The Unforgiven", "Predator"], caption: "Trophy handoff"},
  { file: "IMG_0060 Large.jpeg", year: 2023, teams: ["Predator"], caption: "The Shiva"},
  { file: "IMG_0104 Large.jpeg", year: 2023, teams: ["Paranoid Androids"], caption: "Vegas bound"},
  { file: "IMG_0105 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Thundercunt"], caption: "Excuse me stewardess, I speak jive"},
  { file: "IMG_0109 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Thundercunt"], caption: "Sailor Jerry time"},
  { file: "IMG_0113 Large.jpeg", year: 2023, caption: "HPFFL golf outing"},
  { file: "IMG_0114 Large.jpeg", year: 2023, caption: "Rio Secco"},
  { file: "IMG_0115 Large.jpeg", year: 2023, teams: ["Paranoid Androids"], caption: "Droids and Dogs' brother-in-law"},
  { file: "IMG_0116 Large.jpeg", year: 2023, caption: "Desert Golf"},
  { file: "IMG_0117 Large.jpeg", year: 2023, caption: "Desert Golf Flowers"},
  { file: "IMG_0118 Large.jpeg", year: 2023, caption: "Fore!!"},
  { file: "IMG_0119 Large.jpeg", year: 2023, caption: "What happens at Rio Secco stays at Rio Secco"},
  { file: "IMG_0120 Large.jpeg", year: 2023, teams: ["Paranoid Androids"], caption: "Get me outta this heat"},
  { file: "IMG_0121 Large.jpeg", year: 2023, teams: ["Paranoid Androids"], caption: "Contemplating existence"},
  { file: "IMG_0122 Large.jpeg", year: 2023, teams: ["Paranoid Androids"], caption: "Heat stroke"},
  { file: "IMG_0125 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Reservoir Dogs", "Thundercunt", "Peace Pipes", "Trainwreck", "The Unforgiven", "Predator"], caption: "Vegas Draft Tomahawk time!"},
  { file: "IMG_0131 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Reservoir Dogs", "Thundercunt", "Peace Pipes", "Trainwreck", "The Unforgiven", "Predator"], caption: "Big Pimpin', spending cheese"},
  { file: "IMG_0132 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Reservoir Dogs", "Thundercunt", "Peace Pipes", "Trainwreck", "The Unforgiven", "Predator"], caption: "How suite it is"},
  { file: "IMG_0134 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Reservoir Dogs", "Thundercunt", "Peace Pipes", "Trainwreck", "The Unforgiven", "Predator"], caption: "One more"},
  { file: "IMG_0135 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Reservoir Dogs", "Thundercunt", "Peace Pipes", "Trainwreck", "The Unforgiven", "Predator"], caption: "Suck it in Commish!"},
  { file: "IMG_0137 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Reservoir Dogs", "Thundercunt", "Peace Pipes", "Trainwreck", "The Unforgiven", "Predator"], caption: "Stairway to Heaven, or Herpes"},
  { file: "IMG_0143 Large.jpeg", year: 2023, teams: ["Paranoid Androids", "Reservoir Dogs", "Thundercunt", "Peace Pipes", "Trainwreck", "The Unforgiven", "Predator"], caption: "Bar is open"},
  { file: "IMG_0207 Large.jpeg", year: 2026, teams: ["Reservoir Dogs"], caption: "Dogs' plate #4"},
  { file: "IMG_0213 Large.jpeg", year: 2009, caption: "Thank you for not smoking"},
  { file: "IMG_0256 Large.jpeg", year: 2026, teams: ["Reservoir Dogs"], caption: "Ready for the Lottery"},
  { file: "IMG_0257 Large.jpeg", year: 2026, teams: ["Reservoir Dogs"], caption: "2025 Champ adorned"},
  { file: "IMG_0258 Large.jpeg", year: 2026, teams: ["Reservoir Dogs"], caption: "Pigskin"},
  { file: "IMG_0259 Large.jpeg", year: 2026, teams: ["Grim Outlook"], caption: "Grim forever etched in history"},
  { file: "IMG_0260 Large.jpeg", year: 2026, teams: ["Peace Pipes"], caption: "Bijan!!"},
  { file: "IMG_0261 Large.jpeg", year: 2026, caption: "Crown Jewels ready for 2026 lottery"},
  { file: "IMG_0262 Large.jpeg", year: 2026, teams: ["Reservoir Dogs"], caption: "4-time Champs!"},
  { file: "IMG_0414 Large.jpeg", year: 2022, caption: "Fuck it dude, let's go bowling"},
  { file: "IMG_0415 Large.jpeg", year: 2022, caption: "Bowling balls"},
  { file: "IMG_0417 Large.jpeg", year: 2022, teams: ["Pure Massacre"], caption: "JT!!"},
  { file: "IMG_0433 Large.jpeg", year: 2022, teams: ["The Unforgiven"], caption: "Worm adorned"},
  { file: "IMG_0599 Large.jpeg", year: 2025, teams: ["Grim Outlook"], caption: "Grim plate #1"},
  { file: "IMG_0811 Large.jpeg", year: 2013, teams: ["Thundercunt"], caption: "2012 Champs!"},
  { file: "IMG_0974 Large.jpeg", year: 2011, teams: ["Paranoid Androids"], caption: "Beer goggles"},
  { file: "IMG_1164 Large.jpeg", year: 2025, teams: ["Grim Outlook"], caption: "Ready for 2025 Lottery"},
  { file: "IMG_1165 Large.jpeg", year: 2025, teams: ["Predator", "Dark Horse"], caption: "2025 Lottery"},
  { file: "IMG_1166 Large.jpeg", year: 2025, teams: ["Paranoid Androids"], caption: "First and last time we take a WR #1"},
  { file: "IMG_1167 Large.jpeg", year: 2025, teams: ["Dark Horse"], caption: "Brown Cone forever in the history books"},
  { file: "IMG_1168 Large.jpeg", year: 2025, teams: ["Grim Outlook", "Predator"], caption: "Tower of Power"},
  { file: "IMG_1169 Large.jpeg", year: 2025, teams: ["Grim Outlook"], caption: "Grim adorned"},
  { file: "IMG_1170 Large.jpeg", year: 2025, teams: ["Grim Outlook"], caption: "Safe keeping"},
  { file: "IMG_1177 Large.jpeg", year: 2011, teams: ["Nytebyrd"], caption: "Not sure who it was but was probably Joe Horn or Jeff Garcia"},
  { file: "IMG_1389 Large.jpeg", year: 2006, teams: ["Predator", "Paranoid Androids"], caption: "Droids first chip!"},
  { file: "IMG_1390 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "I will buy all of your motorcycle posters"},
  { file: "IMG_1391 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "Respect your elders"},
  { file: "IMG_1392 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "History in Sharpie form"},
  { file: "IMG_1393 Large.jpeg", year: 2006, teams: ["Paranoid Androids", "Peace Pipes"], caption: "Antonio Gates jersey retirement"},
  { file: "IMG_1394 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "Sharpie time"},
  { file: "IMG_1395 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "Gucci little piggy"},
  { file: "IMG_1396 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "Goose bumps"},
  { file: "IMG_1397 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "Droid Stu"},
  { file: "IMG_1398 Large.jpeg", year: 2006, teams: ["Paranoid Androids", "Dark Horse", "Peace Pipes"], caption: "Mary was not impressed"},
  { file: "IMG_1399 Large.jpeg", year: 2006, teams: ["Paranoid Androids", "Dark Horse", "Inglorious Basterdz"], caption: "Heisman"},
  { file: "IMG_1401 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "Hermetically sealed"},
  { file: "IMG_1402 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "T.O. exorcism Pt. 3"},
  { file: "IMG_1404 Large.jpeg", year: 2006, teams: ["Paranoid Androids"], caption: "T.O. exorcism Pt. 4"},
  { file: "IMG_1574 Large.jpeg", year: 2012, teams: ["War Pigs"], caption: "My guess is it was Arian Foster"},
  { file: "IMG_1991 Large.jpeg", year: 2006, teams: ["Paranoid Androids", "Pipemasters", "Reservoir Dogs", "Chuck 'n Ducks", "War Pigs", "Beefmaster", "Dark Horse", "Predator"], caption: "Back when we used to have decent turnouts to the Lottery"},
  { file: "IMG_1992 Large.jpeg", year: 2006, teams: ["Paranoid Androids", "Pipemasters", "Beefmaster", "Predator"], caption: "Commish plays golf regularly with the ball gir's uncle these days"},
  { file: "IMG_1993 Large.jpeg", year: 2006, teams: ["Paranoid Androids", "Beefmaster", "Predator"], caption: "Pick a winner"},
  { file: "IMG_1994 Large.jpeg", year: 2006, teams: ["Paranoid Androids", "Predator"], caption: "Bingo!"},
  { file: "IMG_2042 Large.jpeg", year: 2013, caption: "Ballsack"},
  { file: "IMG_2043 Large.jpeg", year: 2013, caption: "Crown Jewels"},
  { file: "IMG_2044 Large.jpeg", year: 2013, teams: ["War Pigs"], caption: "Back to back #1's!"},
  { file: "IMG_2060 Large.jpeg", year: 2013, teams: ["Thundercunt"], caption: "First chip etched in history"},
  { file: "IMG_2061 Large.jpeg", year: 2013, teams: ["Thundercunt"], caption: "How do you spell cunt?"},
  { file: "IMG_2062 Large.jpeg", year: 2013, teams: ["Thundercunt"], caption: "First of 3 in 5 years!"},
  { file: "IMG_2193 Large.jpeg", year: 2024, teams: ["Dark Horse"], caption: "Brown Cone plate #2"},
  { file: "IMG_2201 Large.jpeg", year: 2024, teams: ["Predator"], caption: "Always setting a good example for the kids"},
  { file: "IMG_2202 Large.jpeg", year: 2024, teams: ["Dark Horse"], caption: "Joey takes his crown"},
  { file: "IMG_2203 Large.jpeg", year: 2024, teams: ["Predator"], caption: "Chip #2 etched in history"},
  { file: "IMG_2204 Large.jpeg", year: 2024, teams: ["Predator", "Dark Horse"], caption: "Hot potato!"},
  { file: "IMG_2208 Large.jpeg", year: 2024, teams: ["Predator", "Dark Horse"], caption: "Pleasure doing business with ya"},
  { file: "IMG_2211 Large.jpeg", year: 2024, teams: ["Reservoir Dogs"], caption: "Big Johnnie!"},
  { file: "IMG_2212 Large.jpeg", year: 2024, teams: ["Franco's Fur Coats"], caption: "Back to back #1's... Lemme guess, CMC again?"},
  { file: "IMG_2540 Large.jpeg", year: 2014, teams: ["Nytebyrd"], caption: "For sure this one was Andre Johnson"},
  { file: "IMG_2598 Large.jpeg", year: 2014, teams: ["Reservoir Dogs"], caption: "Dogs 2nd sharpie entry"},
  { file: "IMG_2599 Large.jpeg", year: 2014, teams: ["Paranoid Androids", "Thundercunt"], caption: "Commish saw some bad pictures about where the Czar had been"},
  { file: "IMG_3561 Large.jpeg", year: 2015, teams: ["Thundercunt"], caption: "Kiss of death getting the #1 pick after winning the chip, especially when you pick Eddie Lacy"},
  { file: "IMG_4120 Large.jpeg", year: 2016, caption: "Ballsack en route"},
  { file: "IMG_4121 Large.jpeg", year: 2016, teams: ["Franco's Fur Coats"], caption: "Surely this one wasn't CMC... shocker it was Antonio Brown"},
  { file: "IMG_4154 Large.jpeg", year: 2016, teams: ["Thundercunt"], caption: "This sharpie must be out of ink by now"},
  { file: "IMG_4155 Large.jpeg", year: 2016, teams: ["Dallas Plowgirls", "Predator", "Reservoir Dogs", "Fat Lady's Maestro"], caption: "Black Sheep Lodge Draft"},
  { file: "IMG_4156 Large.jpeg", year: 2016, teams: ["Eightball"], caption: "Eightball, side pocket"},
  { file: "IMG_4157 Large.jpeg", year: 2016, teams: ["Eightball"], caption: "How do you spell 8ball?"},
  { file: "IMG_4829 Large.jpeg", year: 2017, teams: ["Paranoid Androids"], caption: "Le'Veon!"},
  { file: "IMG_5191 Large.jpeg", year: 2017, caption: "Shiva idea"},
  { file: "IMG_5205 Large.jpeg", year: 2018, teams: ["Dark Horse", "Paranoid Androids"], caption: "Brown Cone and Commish meet to discuss top secret trophy project"},
  { file: "IMG_5291 Large.jpeg", year: 2018, caption: "Under Construction"},
  { file: "IMG_5299 Large.jpeg", year: 2018, teams: ["Paranoid Androids"], caption: "Droid plate #1"},
  { file: "IMG_5300 Large.jpeg", year: 2018, caption: "Shiny and new"},
  { file: "IMG_5313 Large.jpeg", year: 2018, teams: ["Thundercunt"], caption: "Brand new trophy ready for first handover"},
  { file: "IMG_5314 Large.jpeg", year: 2018, teams: ["Thundercunt"], caption: "Cunts chip #3 to cristen the trophy"},
  { file: "IMG_5315 Large.jpeg", year: 2018, teams: ["Thundercunt"], caption: "Inaugural trophy handoff"},
  { file: "IMG_5316 Large.jpeg", year: 2018, teams: ["Thundercunt"], caption: "Easy there cunt"},
  { file: "IMG_5318 Large.jpeg", year: 2018, teams: ["Thundercunt"], caption: "Because one chair is not enough"},
  { file: "IMG_5796 Large.jpeg", year: 2018, teams: ["Thundercunt"], caption: "Sun bathing"},
  { file: "IMG_5797 Large.jpeg", year: 2018, teams: ["Eightball"], caption: "Le'Veon goes #1 for the second year in a row"},
  { file: "IMG_5798 Large.jpeg", year: 2018, teams: ["Reservoir Dogs"], caption: "Dogs get their first year atop the new trophy"},
  { file: "IMG_5799 Large.jpeg", year: 2018, teams: ["Reservoir Dogs"], caption: "Kids must remain seated"},
  { file: "IMG_5800 Large.jpeg", year: 2018, caption: "Side panel"},
  { file: "IMG_5850 Large.jpeg", year: 2018, teams: ["Trainwreck"], caption: "Trainwreck on the menu in Vegas dispensary"},
  { file: "IMG_5854 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Thundercunt", "The Unforgiven"], caption: "Cosmopolitan gentlemen"},
  { file: "IMG_5855 Large.jpeg", year: 2018, teams: ["Peace Pipes", "Reservoir Dogs", "Thundercunt", "The Makavelli"], caption: "Vegas Draft Pt. 1"},
  { file: "IMG_5856 Large.jpeg", year: 2018, teams: ["The Unforgiven", "Trainwreck"], caption: "Worm explaining how to draft a juggernaut"},
  { file: "IMG_5857 Large.jpeg", year: 2018, teams: ["Peace Pipes", "Reservoir Dogs", "Thundercunt", "The Makavelli"], caption: "Eightball is on the clock!"},
  { file: "IMG_5858 Large.jpeg", year: 2018, teams: ["Peace Pipes", "Reservoir Dogs", "Trainwreck", "Paranoid Androids"], caption: "Stu pointing to left field, where the Droids are about to hit a bomb to in the Draft"},
  { file: "IMG_5859 Large.jpeg", year: 2018, teams: ["Paranoid Androids"], caption: "Droids knowning they're about to draft a chip-winning team from the 16-hole"},
  { file: "IMG_5860 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Peace Pipes", "Thundercunt"], caption: "I put on my robe and wizard hat"},
  { file: "IMG_5862 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Reservoir Dogs", "Peace Pipes", "The Makavelli", "Trainwreck", "The Unforgiven"], caption: "25th Anniversary Vegas Draft crew"},
  { file: "IMG_5865 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Reservoir Dogs", "Peace Pipes", "The Makavelli", "Trainwreck", "The Unforgiven"], caption: "Yeah, yeah you have 3"},
  { file: "IMG_5868 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Reservoir Dogs", "Peace Pipes", "The Makavelli", "Trainwreck", "The Unforgiven"], caption: "No homo"},
  { file: "IMG_5872 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Reservoir Dogs", "Peace Pipes", "The Makavelli", "Trainwreck", "The Unforgiven"], caption: "Collateral damage"},
  { file: "IMG_5873 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Reservoir Dogs", "Peace Pipes", "The Makavelli", "Trainwreck", "The Unforgiven"], caption: "Pretty sure 3 people slept on that couch"},
  { file: "IMG_5874 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Reservoir Dogs", "Peace Pipes", "The Makavelli", "Trainwreck", "The Unforgiven"], caption: "Shots!!"},
  { file: "IMG_5875 Large.jpeg", year: 2018, teams: ["Paranoid Androids", "Reservoir Dogs", "Peace Pipes", "The Makavelli", "Trainwreck", "The Unforgiven"], caption: "Pasties"},
  { file: "IMG_6848 Large.jpeg", year: 2019, teams: ["Peace Pipes"], caption: "JH RIP"},
  { file: "IMG_6849 Large.jpeg", year: 2019, teams: ["Peace Pipes"], caption: "Sloane and Uncle Jason"},
  { file: "IMG_6850 Large.jpeg", year: 2019, teams: ["Peace Pipes"], caption: "Red!!"},
  { file: "IMG_6851 Large.jpeg", year: 2019, teams: ["Peace Pipes"], caption: "It's a sweater!!! What can you say about such men?"},
  { file: "IMG_6876 Large.jpeg", year: 2019, teams: ["The Unforgiven"], caption: "Mahomes!!"},
  { file: "IMG_6899 Large.jpeg", year: 2019, caption: "Mantle piece"},
  { file: "IMG_6910 Large.jpeg", year: 2019, teams: ["Paranoid Androids", "Reservoir Dogs"], caption: "Droids Vegas chip trophy handoff"},
  { file: "IMG_7913 Large.jpeg", year: 2020, teams: ["Paranoid Androids"], caption: "Chip #2 forever in the history books"},
  { file: "IMG_7915 Large.jpeg", year: 2020, teams: ["The Makavelli"], caption: "Makavelli adorned"},
  { file: "IMG_8161 Large.jpeg", year: 2020, teams: ["Paranoid Androids"], caption: "Our finest crystal"},
  { file: "IMG_8167 Large.jpeg", year: 2021, teams: ["Dallas Plowgirls"], caption: "Plowgirls plate #1"},
  { file: "IMG_8175 Large.jpeg", year: 2021, teams: ["Dallas Plowgirls"], caption: "Plowgirls adorned"},
  { file: "IMG_8977 Large.jpeg", year: 2021, caption: "Crown Jewels in the house"},
  { file: "IMG_8982 Large.jpeg", year: 2021, teams: ["Dallas Plowgirls"], caption: "King Henry!"},
  { file: "RX802AB-2 Large.jpeg", year: 2018, caption: "Headpiece"},
  { file: "Screen Shot 2018-01-21 at 7.37.50 PM Large.jpeg", year: 2018, caption: "Living large at the Nugg"},
  { file: "cl Large.jpeg", year: 2016, caption: "Czar Lombardi about to be dismantled"},
  { file: "image0 Large.jpeg", year: 2020, teams: ["Paranoid Androids"], caption: "Zeke!!!"},
  { file: "imagejpeg_0-1 Large.jpeg", year: 2018, caption: "Trophy schematics"},
  { file: "joeyTrophy Large.jpeg", year: 2018, teams: [], caption: ""}
];
